# Generated by Django 3.2 on 2023-09-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='recipe_ingredients_constraint',
        ),
    ]
